library(shiny)
library(readxl)
library(sf)
library(leaflet)
library(leaflet.extras)
library(htmltools)
library(tidyverse)
library(RColorBrewer)
library(shinythemes)
# setwd("H:/Finance/R/Project R/Apps complete/Choropleth-Inflation")
load("EU_0_NUTS_6.Rdata")
load("PPS_GDP_SHP.Rdata")
